webapp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrgController;
use App\Http\Controllers\InoutController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\MediafileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\PostController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\PostController::class, 'index']);
Route::prefix('posts')->middleware('auth')->group(function () {
    Route::get('/{id?}', [PostController::class, 'show'])->where('id', '[0-9]+')->name('posts');
    Route::get('/{id}/edit', [PostController::class, 'edit'])->where('id', '[0-9]+')->name('editpost');
    Route::get('/add', [PostController::class, 'edit'])->name('addpost');
});

Route::prefix('orgs')->middleware('auth')->group(function () {
    Route::get('/{id?}', [OrgController::class, 'show'])->where('id', '[0-9]+')->name('orgs');
    Route::get('/{id}/edit', [OrgController::class, 'edit'])->where('id', '[0-9]+')->name('editorg');
    Route::get('/add', [OrgController::class, 'edit'])->name('addorg');
});

Route::prefix('inouts')->middleware('auth')->group(function () {
    Route::get('/{id?}', [InoutController::class, 'show'])->where('id', '[0-9]+')->name('inouts');
    Route::get('/add', [InoutController::class, 'edit'])->name('addinout');
    Route::get('/balance', [InoutController::class, 'show_balance'])->name('balance');
    Route::post('/add', [InoutController::class, 'store'])->name('addinout');
    Route::post('/getkvit', [InoutController::class, 'getkvit'])->name('getkvit');
});

Route::prefix('tickets')->middleware('auth')->group(function () {
    Route::post('/buy', [TicketController::class, 'show'])->name('ticketbuy');
    Route::post('/buysubmit', [TicketController::class, 'store'])->name('ticketbuysubmit');
});

Route::prefix('mediafiles')->middleware('auth')->group(function () {
    Route::get('/{id?}', [MediafileController::class, 'show'])->where('id', '[0-9]+')->name('mediafiles');
    Route::get('/{id}/edit', [MediafileController::class, 'edit'])->where('id', '[0-9]+')->name('editmediafile');
    Route::get('/add', [MediafileController::class, 'edit'])->name('addmediafile');
});

Route::prefix('users')->middleware('auth')->group(function () {
    Route::get('/{id?}', [UserController::class, 'show'])->where('id', '[0-9]+')->name('users');
    Route::get('/{id}/edit', [UserController::class, 'edit'])->where('id', '[0-9]+')->name('edituser');
});

Route::get('/useroauth/{provider}', [App\Http\Controllers\UserOAuth::class, 'auth']);
Route::get('/LoginViaVk', function () { return Socialite::driver('vkontakte')->redirect(); })->name('LoginViaVk');

webapp/app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Models\Mediafile;
use App\Models\User;
use App\Models\Org;
use App\Models\Ticket;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

class Post extends Model
{
    use HasFactory;

    public function picture() {
        return $this->belongsTo(Mediafile::class);
    }

    public function video() {
        return $this->belongsTo(Mediafile::class);
    }

    public function videopriview() {
        return $this->belongsTo(Mediafile::class);
    }

    public function getStreamStringAttribute() {
        return "{$this->stream_name}/{$this->stream_token}";
    }

    public function getCvAttribute() {
        return $this->cv_before + $this->cv_live + $this->cv_after;
    }

    public function tickets()
    {
        return $this->hasMany(Ticket::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function org() {
        return $this->belongsTo(Org::class);
    }

    protected static function booted()
    {
        static::creating(function (Post $post) {
            $post->user_id = Auth::id();
            $post->org_id = Auth::user()->org_id;
            $post->stream_name = Str::uuid();
            $post->stream_token = Str::random(32);
        });
    }
}

webapp/app/Http/Livewire/EditPost.php
<?php

namespace App\Http\Livewire;

use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use Livewire\Component;
use Livewire\WithFileUploads;
use App\Models\Mediafile;
use App\Models\Post;
use App\Jobs\StartRec;
use App\Jobs\StopRec;
use App\Jobs\StopRTMP;

class EditPost extends Component
{
    use WithFileUploads;

    public Post $post;
    public $picturefile;
    public Mediafile $picture;
    public $edit;
    public $inputcolor;
    public $stream_token;
    public $startrec_dis = 'disabled';
    public $stoprec_dis = 'disabled';

    protected $rules = [
        'post.autorecord' => ['nullable', 'boolean'],
        'post.title1' => ['required', 'min:1'],
        'post.title2' => ['nullable', 'string'],
        'post.dt_begin' => ['required', 'date'],
        'post.dt_end' => ['required', 'date'],
        'post.price' => ['required', 'numeric'],
        'post.timeleft' => ['nullable', 'numeric'],
        'post.body' => ['nullable', 'string'],
        'inputcolor' => ['nullable', 'string', 'max:9', 'regex:/^#(?:[0-9a-fA-F]{3,4}){1,2}$/i'],
        'picturefile' => ['nullable', 'image', 'max:2048'],
    ];

    public function mount() {
        if ($this->edit == 2) {
            $this->post = new Post;
            $this->post->autorecord = false;
        }
        if ($this->edit == 1) {
            $this->stream_token = $this->post->stream_token;
        }
    }

    public function refreshbuttons() {
        if ($this->edit == 1) {
            if ($this->post->rtmp_status == true) {
                if ($this->post->record == true) {
                    $this->startrec_dis = 'disabled';
                    $this->stoprec_dis = '';
                } else {
                    $this->startrec_dis = '';
                    $this->stoprec_dis = 'disabled';
                }
            } else {
                $this->startrec_dis = 'disabled';
                $this->stoprec_dis = 'disabled';
            }
        }
    }

    public function save() {
        $this->validate();
        $this->post->color = substr($this->inputcolor, 1);
        if ($this->picturefile)
        {
            $tempuri = $this->picturefile->store('public');
            $temphash = hash_file('sha256', Storage::path($tempuri), true);
            $efile = Mediafile::where('sha256checksum', $temphash)->first();
            if ($efile) {
                $this->post->picture_id = $efile->id;
                Storage::delete($tempuri);
            } else {
                $this->picture = new Mediafile;
                $this->picture->uri = $tempuri;
                $this->picture->sha256checksum = $temphash;
                $this->picture->save();
                $this->post->picture_id = $this->picture->id;
            }
            $this->picturefile->delete();
        }
        if ($this->edit == 1) {
            $this->post->stream_token = $this->stream_token;
        }
        $this->post->save();
        if (($this->edit == 2) && ($this->post->id > 0)) {
            $this->stream_token = $this->post->stream_token;
            $this->edit = 1;
        }
    }

    public function gentoken() {
        $this->stream_token = Str::random(32);
    }

    public function startrec() {
        StartRec::dispatch($this->post);
        $this->startrec_dis = 'disabled';
        $this->stoprec_dis = '';
    }

    public function stoprec() {
        StopRec::dispatch($this->post);
        $this->startrec_dis = '';
        $this->stoprec_dis = 'disabled';
    }

    public function stop() {
        StopRTMP::dispatch($this->post);
    }

    public function render()
    {
        return view('livewire.edit-post');
    }
}

webapp/app/Http/Livewire/ShowInout.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Inout;

class ShowInout extends Component
{

    public Inout $inout;

    public function delete() {
        $this->inout->delete();
    }

    public function render()
    {
        return view('livewire.show-inout');
    }
}

webapp/app/Http/Livewire/ShowMediafile.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Mediafile;

class ShowMediafile extends Component
{

    public Mediafile $mediafile;

    public function delete() {
        $this->mediafile->delete();
    }

    public function render()
    {
        return view('livewire.show-mediafile');
    }
}

webapp/app/Http/Livewire/ShowOrg.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Org;

class ShowOrg extends Component
{
    public Org $org;

    public function delete() {
        $this->org->delete();
    }

    public function render()
    {
        return view('livewire.show-org');
    }
}

webapp/app/Http/Livewire/ShowPost.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\Post;

class ShowPost extends Component
{
    public Post $post;

    public function delete() {
        $this->post->delete();
    }

    public function render()
    {
        return view('livewire.show-post');
    }
}

webapp/app/Http/Livewire/ShowUser.php
<?php

namespace App\Http\Livewire;

use Livewire\Component;
use App\Models\User;

class ShowUser extends Component
{
    public User $user;

    public function render()
    {
        return view('livewire.show-user');
    }
}

webapp/resources/views/livewire/edit-post.blade.php
<form wire:submit.prevent="save" class="mt-2">
    @if ($edit == 1)
    @if ($post->rtmp_status == true)
    <div class="mb-3" wire:ignore>
        <video-js style="display: block; width: 100%" class="vjs-theme-city" id="hls" controls preload="none" @if($post->picture)poster="{{ Storage::url($post->picture->uri) }}"@endif data-setup='{}'>
            <source src="{{ env('APP_URL').':81/hls/'.$post->stream_name }}" type="application/x-mpegURL">
        </video-js>
    </div>
    @endif
    @if (($post->file_preparation == true) and ($post->rtmp_status == false))
    <div class="mb-3 alert alert-warning" role="alert">Идёт обработка записанных данных.</div>
    @endif
    @if (($post->file_preparation == false) and ($post->rtmp_status == false) and ($post->video))
    <div class="mb-3" wire:ignore>
        <video-js style="display: block; width: 100%" class="vjs-theme-city" id="hls" controls preload="none" @if($post->picture)poster="{{ Storage::url($post->picture->uri) }}"@endif data-setup='{}'>
            <source src="{{ Storage::url($post->video->uri) }}" type="video/mp4">
        </video-js>
    </div>
    @endif
    <div class="mb-3" wire:poll="refreshbuttons">
        RTMP: {{ $post->rtmp_ip_sender }}@if($post->rtmp_status )<i class="bi bi-brightness-low-fill fs-4" style="color: green"></i>{{ $post->timepass }}@else<i class="bi bi-brightness-low-fill fs-4" style="color: red"></i>@endif
        <button type="button" class="btn btn-outline-danger" wire:click="stop">Стоп</button>
        <button type="button" class="btn btn-primary" wire:click="startrec" {{ $startrec_dis }}>Начать запись</button>
        <button type="button" class="btn btn-secondary" wire:click="stoprec" {{ $stoprec_dis }}>Остановить запись</button>
    </div>
    @endif
    <div class="mb-3 form-check">
        <input type="checkbox" class="form-check-input" id="autorecord" wire:model.defer="post.autorecord">
        <label for="autorecord" class="form-check-label">Начать запись при поступлении данных RTMP</label>
    </div>
    <div class="mb-3 form-floating">
        <input type="text" class="form-control" id="title1" wire:model.defer="post.title1" required>
        <label for="title1" class="form-label">Заголовок 1</label>
    </div>
    <div class="mb-3 form-floating">
        <input type="text" class="form-control" id="title2" wire:model.defer="post.title2">
        <label for="title2" class="form-label">Заголовок 2</label>
    </div>
    <div class="mb-3 form-floating">
        <input type="datetime-local" class="form-control" id="dt_begin" wire:model.defer="post.dt_begin" required>
        <label for="dt_begin" class="form-label">Начало</label>
    </div>
    <div class="mb-3 form-floating">
        <input type="datetime-local" class="form-control" id="dt_end" wire:model.defer="post.dt_end" required>
        <label for="dt_end" class="form-label">Конец</label>
    </div>
    <div class="mb-3 form-floating">
        <input type="number" class="form-control" id="price" wire:model.defer="post.price" required>
        <label for="price" class="form-label">Цена</label>
    </div>
    <div class="mb-3 form-floating">
        <input type="number" class="form-control" id="timeleft" wire:model.defer="post.timeleft">
        <label for="timeleft" class="form-label">Таймлефт</label>
    </div>
    <div class="mb-3">
        <p>В подписках</p>
        <div class="form-check">
            <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault">
            <label class="form-check-label" for="flexCheckDefault">Подписка 1</label>
        </div>
    </div>
    <div class="mb-3 form-floating">
        <textarea class="form-control" id="body" style="height: 200px" wire:model.defer="post.body"></textarea>
        <label for="body" class="form-label">Текст</label>
    </div>
    <div class="mb-3 form-floating">
        <div class="color-picker"></div>
        <input type="text" class="form-control" id="color" maxlength="9" value="" wire:model.defer="inputcolor">
        <label for="color" class="form-label my-3">Цвет</label>
    </div>
    <div class="mb-3">
        <input type="file" accept="image/*" class="form-control" id="picturefile" wire:model.defer="picturefile">
        <label for="picturefile" class="form-label">Картинка</label>
    </div>
    <div class="mb-3 form-floating">
        <input type="text" class="form-control" id="stream_name" readonly value="{{ env('RTMP_INGEST').'/'.$post->stream_name }}">
        <label for="stream_name" class="form-label">Путь/имя трансляции</label>
    </div>
    <div class="mb-3 form-floating">
        <input type="text" class="form-control" id="stream_token" readonly value="{{ $stream_token }}">
        <label for="stream_token" class="form-label">Ключ трансляции</label>
        @if ($edit == 1) <button type="button" class="btn btn-secondary btn-sm my-1" wire:click="gentoken">Новый ключ</button> @endif
    </div>
    <div class="mb-3 form-floating">
        <input type="text" class="form-control" id="stream_string" readonly value="{{ env('RTMP_INGEST').'/'.$post->stream_name.'?token='.$post->stream_token }}">
        <label for="stream_string" class="form-label">Путь/имя/ключ трансляции</label>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn btn-outline-primary">@if ($edit == 2) Создать @endif @if ($edit == 1) Изменить @endif</button>
        <button type="button" class="btn btn-outline-success" onclick='location.href="{{ route('posts', ['id' => $post->id]) }}"'>Просмотреть</button>
    </div>
</form>

webapp/resources/views/livewire/show-mediafile.blade.php
@if (in_array(Auth::user()->access_level, [1, 3, 4]))
<div class="card my-4">
    <div class="card-header">{{ $mediafile->id }} Автор: {{ $mediafile->user->name }} {{ $mediafile->org->brandtitle }} Создано: {{ date_format(date_create($mediafile->created_at), 'd.m.Y H:i:s') }}, изменён {{ date_format(date_create($mediafile->updated_at), 'd.m.Y H:i:s') }}.</div>
    <div class="card-body">
        <dl class="row">
            <dt class="col-sm-3">Контрольная сумма SHA-256</dt>
            <dd class="col-sm-9">{{ bin2hex($mediafile->sha256checksum) }}</dd>
            <dt class="col-sm-3">URI</dt>
            <dd class="col-sm-9"><a target="_blank" href="{{ Storage::url($mediafile->uri) }}">{{ Storage::url($mediafile->uri) }}</a></dd>
        </dl>
    </div>
    <div class="card-footer">
        <button type="button" class="btn btn-outline-danger" wire:click="delete">Удалить</button>
    </div>
</div>
@endif

webapp/resources/views/livewire/show-org.blade.php
<div class="card my-4">
    <div class="card-header">{{ $org->title }}. Создано: {{ date_format(date_create($org->created_at), 'd.m.Y H:i:s') }}, изменёно {{ date_format(date_create($org->updated_at), 'd.m.Y H:i:s') }}.</div>
    <div class="card-body">
        <h5 class="card-title">{{ $org->brandtitle }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ $org->fulltitle }}</h6>
        <dl class="row">
            <dt class="col-sm-3">ОГРН(ЮЛ/ИП)</dt>
            <dd class="col-sm-9">{{ $org->ogrn }}</dd>
            <dt class="col-sm-3">ИНН</dt>
            <dd class="col-sm-9">{{ $org->inn }}</dd>
            <dt class="col-sm-3">КПП</dt>
            <dd class="col-sm-9">{{ $org->kpp }}</dd>
            <dt class="col-sm-3">Адрес регистрации</dt>
            <dd class="col-sm-9">{{ $org->address }}</dd>
            @if(in_array(Auth::user()->access_level, [2, 3, 4]))
            <dt class="col-sm-3">Статус плательщиков, что платят ЮЛ(ИП)</dt>
            <dd class="col-sm-9">{{ $org->drawer_status }}</dd>
            <dt class="col-sm-3">Наименование получателя платежей</dt>
            <dd class="col-sm-9">{{ $org->fintitle }}</dd>
            <dt class="col-sm-3">Номер расчётного(казначейского) счёта (реквизит «17» платежного поручения)</dt>
            <dd class="col-sm-9">{{ $org->personal_acc }}</dd>
            <dt class="col-sm-3">Наименование банка получателя</dt>
            <dd class="col-sm-9">{{ $org->bank_name }}</dd>
            <dt class="col-sm-3">БИК</dt>
            <dd class="col-sm-9">{{ $org->bic }}</dd>
            <dt class="col-sm-3">Корреспондентский счёт (ЕКС) (реквизит «15» платежного поручения)</dt>
            <dd class="col-sm-9">{{ $org->corresp_acc }}</dd>
            <dt class="col-sm-3">Код бюджетной классификации</dt>
            <dd class="col-sm-9">{{ $org->kbk }}</dd>
            <dt class="col-sm-3">Назначение кода бюджетной классификации</dt>
            <dd class="col-sm-9">{{ $org->titlekbk }}</dd>
            <dt class="col-sm-3">Общероссийский классификатор территорий муниципальных образований (ОКТМО)</dt>
            <dd class="col-sm-9">{{ $org->oktmo }}</dd>
            <dt class="col-sm-3">Назначение платежа</dt>
            <dd class="col-sm-9">{{ $org->purpose }}</dd>
            <dt class="col-sm-3">E-mail</dt>
            <dd class="col-sm-9">{{ $org->email }}</dd>
            <dt class="col-sm-3">Телефон</dt>
            <dd class="col-sm-9">{{ $org->tel }}</dd>
            @endif
        </dl>
    </div>
    <div class="card-footer">
        @if(Auth::user()->access_level == 4)
        <button type="button" class="btn btn-outline-warning">Изменить</button>
        <button type="button" class="btn btn-outline-danger">Удалить</button>
        @endif
    </div>
</div>

webapp/resources/views/livewire/show-post.blade.php
<div class="card my-4">
    <div class="card-header">@if (in_array(Auth::user()->access_level, [1, 3, 4])) Автор: {{ $post->user->name }} @endif {{ $post->org->brandtitle }} Создано: {{ date_format(date_create($post->created_at), 'd.m.Y H:i:s') }}, изменён {{ date_format(date_create($post->updated_at), 'd.m.Y H:i:s') }}. {{ $post->cv }} просмотров, из них {{ $post->cv_before }}, инлайв {{ $post->cv_live }}, после {{ $post->cv_after }} </div>
    @if (($post->picture) and (date_create($post->dt_begin) > now())) <img src="{{ Storage::url($post->picture->uri) }}" class="card-img-top"> @endif
    <div class="card-body">
    @if(count($post->tickets) > 0)
        @if (($post->rtmp_status == true) and (date_create($post->dt_begin) < now()) and (date_create($post->dt_end) > now()))
        <div class="mb-3" wire:ignore>
            <video-js style="display: block; width: 100%" class="vjs-theme-city" id="hls" controls preload="none" @if($post->picture)poster="{{ Storage::url($post->picture->uri) }}"@endif data-setup='{}'>
                <source src="{{ env('APP_URL').':81/hls/'.$post->stream_name }}" type="application/x-mpegURL">
            </video-js>
        </div>
        @endif
        @if (($post->file_preparation == true) and ($post->rtmp_status == false))
        <div class="mb-3 alert alert-warning" role="alert">Идёт обработка записанных данных.</div>
        @endif
        @if (($post->file_preparation == false) and ($post->rtmp_status == false) and ($post->video) and (date_create($post->dt_end) < now()))
        <div class="mb-3" wire:ignore>
            <video-js style="display: block; width: 100%" class="vjs-theme-city" id="hls" controls preload="none" @if($post->picture)poster="{{ Storage::url($post->picture->uri) }}"@endif data-setup='{}'>
                <source src="{{ Storage::url($post->video->uri) }}" type="video/mp4">
            </video-js>
        </div>
        @endif
    @endif
        <h5 class="card-title">{{ $post->title1 }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ $post->title2 }}</h6>
        <dl class="row">
            <dt class="col-sm-3">Начало</dt>
            <dd class="col-sm-9">{{ date_format(date_create($post->dt_begin), 'd.m.Y H:i:s') }}</dd>
            <dt class="col-sm-3">Конец</dt>
            <dd class="col-sm-9">{{ date_format(date_create($post->dt_end), 'd.m.Y H:i:s') }}</dd>
            <dt class="col-sm-3">Цена</dt>
            <dd class="col-sm-9">{{ $post->price }}</dd>
            <dt class="col-sm-3">Таймлефт</dt>
            <dd class="col-sm-9">{{ $post->timeleft }}</dd>
            <dt class="col-sm-3">В подписках</dt>
            <dd class="col-sm-9"></dd>
        </dl>
        <p class="card-text">{{ $post->body }}</p>
        @if (in_array(Auth::user()->access_level, [1, 3, 4]))
        <dl class="row">
            <dt class="col-sm-3">Путь/имя трансляции</dt>
            <dd class="col-sm-9">{{ env('RTMP_INGEST').'/'.$post->stream_name }}</dd>
            <dt class="col-sm-3">Ключ трансляции</dt>
            <dd class="col-sm-9">{{ $post->stream_token }}</dd>
            <dt class="col-sm-3">Путь/имя/ключ</dt>
            <dd class="col-sm-9">{{ env('RTMP_INGEST').'/'.$post->stream_name.'?token='.$post->stream_token }}</dd>
        </dl>
        @endif
    </div>
    <div class="card-footer">
        @if(in_array(Auth::user()->access_level, [1, 3, 4]))
        <span wire:poll>RTMP: {{ $post->rtmp_ip_sender }}@if($post->rtmp_status )<i class="bi bi-brightness-low-fill fs-4" style="color: green"></i>{{ $post->timepass }}@else<i class="bi bi-brightness-low-fill fs-4" style="color: red"></i>@endif</span>
        <button type="button" class="btn btn-outline-warning" onclick='location.href="{{ route('editpost', ['id' => $post->id]) }}"'>Изменить</button>
        <button type="button" class="btn btn-outline-danger" wire:click="delete">Удалить</button>
        @endif
        @if(count($post->tickets) > 0) Билет куплен.
        @else
        <form id="ticketbuy-org{{$post->org_id}}-post{{$post->id}}" method="POST" action="{{ route('ticketbuy') }}">@csrf
            <input name="org_id" type="hidden" value="{{$post->org_id}}">
            <input name="post_id" type="hidden" value="{{$post->id}}">
            <input name="user_id" type="hidden" value="{{Auth::id()}}">
            <button type="submit" class="btn btn-outline-success">Купить</button>
        </form>
        @endif
    </div>
</div>

webapp/resources/views/livewire/show-user.blade.php
<div class="card my-4">
    <div class="card-header">ID пользователя: {{ $user->id }}, создан: {{ date_format(date_create($user->created_at), 'd.m.Y H:i:s') }}, изменён {{ date_format(date_create($user->updated_at), 'd.m.Y H:i:s') }}</div>
    <div class="card-body">
        <h5 class="card-title">{{ $user->name }}</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ $user->email }}</h6>
        <dl class="row">
            <dt class="col-sm-3">Уровень прав</dt>
            <dd class="col-sm-9">{{ $user->AL }}</dd>
            <dt class="col-sm-3">E-mail проверен</dt>
            <dd class="col-sm-9">{{ date_format(date_create($user->email_verified_at), 'd.m.Y H:i:s') }}</dd>
            <dt class="col-sm-3">Google ID</dt>
            <dd class="col-sm-9">{{ $user->google_id }}</dd>
            <dt class="col-sm-3">VK ID</dt>
            <dd class="col-sm-9">{{ $user->vk_id }}</dd>
            <dt class="col-sm-3">Yandex ID</dt>
            <dd class="col-sm-9">{{ $user->yandex_id }}</dd>
            <dt class="col-sm-3">Instagram ID</dt>
            <dd class="col-sm-9">{{ $user->instagram_id }}</dd>
            <dt class="col-sm-3">Организация</dt>
            <dd class="col-sm-9">@if($user->org){{ $user->org->title }}@endif</dd>
        </dl>
    </div>
    <div class="card-footer">
        @if (in_array(Auth::user()->access_level, [3, 4]))
        <button type="button" class="btn btn-outline-warning" onclick='location.href="{{ route('edituser', ['id' => $user->id]) }}"'>Изменить</button>
        <button type="button" class="btn btn-outline-danger">Удалить</button>
        @endif
    </div>
</div>