webapp/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\PostController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrgController;
use App\Http\Controllers\InoutController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\MediafileController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\PostController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\PostController::class, 'index']);
Route::prefix('posts')->middleware('auth')->group(function () {
    Route::get('/{id?}', [PostController::class, 'show'])->where('id', '[0-9]+')->name('posts');
    Route::get('/{id}/edit', [PostController::class, 'edit'])->where('id', '[0-9]+')->name('editpost');
    Route::get('/add', [PostController::class, 'edit'])->name('addpost');
});

Route::prefix('orgs')->middleware('auth')->group(function () {
    Route::get('/{id?}', [OrgController::class, 'show'])->where('id', '[0-9]+')->name('orgs');
    Route::get('/{id}/edit', [OrgController::class, 'edit'])->where('id', '[0-9]+')->name('editorg');
    Route::get('/add', [OrgController::class, 'edit'])->name('addorg');
});

Route::prefix('inouts')->middleware('auth')->group(function () {
    Route::get('/{id?}', [InoutController::class, 'show'])->where('id', '[0-9]+')->name('inouts');
    Route::get('/add', [InoutController::class, 'edit'])->name('addinout');
    Route::get('/balance', [InoutController::class, 'show_balance'])->name('balance');
    Route::post('/add', [InoutController::class, 'store'])->name('addinout');
    Route::post('/getkvit', [InoutController::class, 'getkvit'])->name('getkvit');
});

Route::prefix('tickets')->middleware('auth')->group(function () {
    Route::post('/buy', [TicketController::class, 'show'])->name('ticketbuy');
    Route::post('/buysubmit', [TicketController::class, 'store'])->name('ticketbuysubmit');
});

Route::prefix('mediafiles')->middleware('auth')->group(function () {
    Route::get('/{id?}', [MediafileController::class, 'show'])->where('id', '[0-9]+')->name('mediafiles');
    Route::get('/{id}/edit', [MediafileController::class, 'edit'])->where('id', '[0-9]+')->name('editmediafile');
    Route::get('/add', [MediafileController::class, 'edit'])->name('addmediafile');
});

Route::prefix('users')->middleware('auth')->group(function () {
    Route::get('/{id?}', [UserController::class, 'show'])->where('id', '[0-9]+')->name('users');
    Route::get('/{id}/edit', [UserController::class, 'edit'])->where('id', '[0-9]+')->name('edituser');
});

Route::get('/useroauth/{provider}', [App\Http\Controllers\UserOAuth::class, 'auth']);
Route::get('/LoginViaVk', function () { return Socialite::driver('vkontakte')->redirect(); })->name('LoginViaVk');

webapp/app/Models/Inout.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;
use App\Models\User;
use App\Models\Org;

class Inout extends Model
{
    use HasFactory;

    protected $fillable = ['title_doc', 'number_doc', 'date_doc', 'user_id', 'sum'];

    protected $attributes = ['sum' => 0, 'total' => 0];

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function org()
    {
        return $this->belongsTo(Org::class);
    }

    public function getBeforetotalAttribute()
    {
        $bi = self::where(['user_id' => $this->user_id, 'org_id' => $this->org_id])->where('id', '<', $this->id)->orderByDesc('id')->latest()->firstOr(function () {return new Inout;});
        return $bi->total;
    }

    public function getLasttotalAttribute()
    {
        $li = self::where(['user_id' => $this->user_id, 'org_id' => $this->org_id])->orderByDesc('id')->latest()->firstOr(function () {return new Inout;});
        return $li->total;
    }

    public function getBalanceAttribute()
    {
        return $this->lasttotal + $this->sum;
    }

    public function scopeGetBalances($query)
    {
        $a = DB::select(DB::raw('SELECT max(`id`) AS `mid` FROM `inouts` GROUP BY `org_id`,`user_id`'));
        $b = [];
        foreach ($a as $ae)
        {
            $b[] = $ae->mid;
        }
        return $query->whereIn('id', $b);
    }

    public function scopeLimitByUser($query)
    {
        $us = User::select('id')->limitAL()->get();
        $c = [];
        foreach ($us as $u)
        {
            $c[] = $u->id;
        }
        return $query->whereIn('user_id', $c);
    }
}

webapp/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container"><div class="row justify-content-center"><div class="w-100">
    <section id="sectioncarousel">
        <div id="carouselposts" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
            @foreach ($posts as $post)
                <div class="rounded-3 carousel-item @if($lpid == $post->id)active @endif vh80 cbi" @if($post->picture) style="background-image:url({{Storage::url($post->picture->uri)}})" @endif>
                    <div class="carousel-caption d-block">
                        <h1>{{ $post->title1 }}</h1>
                        <h4>{{ $post->title2 }}</h4>
                        <p>{{ date_format(date_create($post->dt_begin), 'd.m.Y H:i') }}</p>
                        <a type="button" class="btn btn-danger btn-lg mt-4" href="{{route('posts',$post->id)}}">Смотреть</a>
                    </div>
                </div>
            @endforeach
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselposts" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Предыдущий</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselposts" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Следующий</span>
            </button>
        </div>
    </section>
    <section id="sectionnowevents">
        <div class="d-block rounded-pill bga py-1 mt-4 text-center"><h2>Сейчас</h2></div>
        <div class="justify-content-between card-group">
        @foreach($postsnow as $postnow)
            <a href="{{route('posts',$postnow->id)}}" class="card m-2 rounded-3 bga text-decoration-none link-dark" style="min-width: 240px">
                @if($postnow->picture) <img src="{{Storage::url($postnow->picture->uri)}}" class="rounded-3 card-img-top"> @endif
                <div class="card-body">
                    <div><b>{{$postnow->title1}}</b></div>
                    <div>{{ date_format(date_create($postnow->dt_begin), 'd.m.Y H:i') }}</div>
                </div>
            </a>
        @endforeach
        @if(count($postsnow) < 1) Ничего нет. @endif
        </div>
    </section>
    <section id="sectionfutureevents">
        <div class="d-block rounded-pill bga py-1 mt-4 text-center"><h2>Предстоящие события</h2></div>
        <div class="justify-content-between card-group">
        @foreach($postsfuture as $postfuture)
            <a href="{{route('posts',$postfuture->id)}}" class="card m-2 rounded-3 bga text-decoration-none link-dark" style="min-width: 240px">
                @if($postfuture->picture) <img src="{{Storage::url($postfuture->picture->uri)}}" class="rounded-3 card-img-top"> @endif
                <div class="card-body">
                    <div><b>{{$postfuture->title1}}</b></div>
                    <div>{{ date_format(date_create($postfuture->dt_begin), 'd.m.Y H:i') }}</div>
                </div>
            </a>
        @endforeach
        @if(count($postsfuture) < 1) Ничего нет. @endif
        </div>
    </section>
    <section id="sectionpastevents">
        <div class="d-block rounded-pill bga py-1 mt-4 text-center"><h2>Прошедшие события</h2></div>
        <div class="justify-content-between card-group">
        @foreach($postspast as $postpast)
            <a href="{{route('posts',$postpast->id)}}" class="card m-2 rounded-3 bga text-decoration-none link-dark" style="min-width: 240px">
                @if($postpast->picture) <img src="{{Storage::url($postpast->picture->uri)}}" class="rounded-3 card-img-top"> @endif
                <div class="card-body">
                    <div><b>{{$postpast->title1}}</b></div>
                    <div>{{ date_format(date_create($postpast->dt_begin), 'd.m.Y H:i') }}</div>
                </div>
            </a>
        @endforeach
        @if(count($postspast) < 1) Ничего нет. @endif
        </div>
    </section>
    @if(count($posts) > 1) {{$posts->links()}} @endif
    @if(count($posts) < 1) Ничего нет. @endif
</div></div></div>
@endsection

webapp/resources/views/inout-add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <h3>Ввод операции</h3>
            <form class="mt-2" method="POST" action="{{ route('addinout') }}">@csrf
                <div class="mb-3 form-floating">
                    <input type="text" class="form-control" id="title_doc" name="title_doc" required>
                    <label for="title_doc" class="form-label">Наименование документа</label>
                </div>
                <div class="mb-3 form-floating">
                    <input type="text" class="form-control" id="number_doc" name="number_doc" required>
                    <label for="number_doc" class="form-label">Номер документа</label>
                </div>
                <div class="mb-3 form-floating">
                    <input type="date" class="form-control" id="date_doc" name="date_doc" required>
                    <label for="date_doc" class="form-label">Дата документа</label>
                </div>
                <div class="mb-3 form-floating">
                    <input type="number" class="form-control" id="user_id" name="user_id" required>
                    <label for="user_id" class="form-label">ID пользователя</label>
                </div>
                <div class="mb-3 form-floating">
                    <input type="number" min="0" value="0" step="0.01" class="form-control" id="sum" name="sum" required>
                    <label for="sum" class="form-label">Сумма (в рублях РФ)</label>
                </div>
                <button type="submit" class="btn btn-primary">Провести</button>
            </form>
        </div>
    </div>
</div>
@endsection

webapp/resources/views/inout-balance.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 bg-white rounded-3">
        <table class="table table-striped my-4">
            <thead><tr><th>Пользователь (ID)</th><th>Организация (ИНН)</th><th>Баланс</th><th>Действие</th><th>ID / дата / сумма последней операции</th></tr></thead>
            <tbody>
            @foreach ($inouts as $inout)
                <tr><td>{{ $inout->user->name }} ({{ $inout->user->id }})</td><td>{{ $inout->org->title }} ({{ $inout->org->inn }})</td><td>{{ $inout->total }}</td><td>
                <form id="topupbalance-user{{$inout->user_id}}-org{{$inout->org_id}}" class="mt-2" target="_blank" method="POST" action="{{ route('getkvit') }}">@csrf
                    <input name="user_id" type="hidden" value="{{$inout->user_id}}">
                    <input name="org_id" type="hidden" value="{{$inout->org_id}}">
                    <button type="submit" class="btn btn-outline-success">Пополнить</button>
                </form>
                </td><td>{{ $inout->id }} / {{ date('d.m.Y', strtotime($inout->created_at)) }} / {{ $inout->sum }}</td></tr>
            @endforeach
            </tbody>
        </table>
        {{ $inouts->links() }}
        @if (count($inouts) < 1) Нет операций. @endif
        </div>
    </div>
</div>
@endsection

webapp/resources/views/inout.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 bg-white rounded-3">
        @if(in_array(Auth::user()->access_level, [2, 3, 4])) <button type="button" class="btn btn-outline-primary mt-4" onclick='location.href="{{ route('addinout') }}"'>Добавить операцию</button> @endif
        <table class="table table-striped">
            <thead><tr><th>ID</th><th>Организация</th><th>Наименование</th><th>Номер</th><th>Дата</th><th>ID билета к посту</th><th>ID билета к подписке</th><th>Пользователь</th><th>Сальдо до</th><th>Сумма (₽)</th><th>Сальдо после</th><th>Внесена</th></tr><thead>
            <tbody>
            @foreach ($inouts as $inout)
                <tr><td>{{ $inout->id }}</td><td><a href="{{ route('orgs', $inout->org_id) }}">{{ $inout->org->inn }}</a></td><td>{{ $inout->title_doc }}</td><td>{{ $inout->number_doc }}</td><td>{{ date('d.m.Y', strtotime($inout->date_doc)) }}</td><td>{{ $inout->ticket_id }}</td><td>{{ $inout->sub_accesse_id }}</td><td><a href="{{ route('users', $inout->user_id) }}">{{ $inout->user_id }}</a></td><td>{{ $inout->beforetotal }}</td><td>{{ $inout->sum }}</td><td>{{ $inout->total }}</td><td>{{ date('d.m.Y', strtotime($inout->created_at)) }}</td></tr>
            @endforeach
            </tbody>
        </table>
        {{ $inouts->links() }}
        @if (count($inouts) < 1) Нет операций. @endif
        </div>
    </div>
</div>
@endsection

webapp/resources/views/mediafile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
        <button type="button" class="btn btn-outline-primary my-8" onclick='location.href="{{ route('addmediafile') }}"'>Добавить медиафайл</button>
        @if ($edit == 0)
            @foreach ($mediafiles as $mediafile)
                <livewire:show-mediafile :mediafile="$mediafile" :wire:key="$mediafile->id">
            @endforeach
            {{ $mediafiles->links() }}
            @if (count($mediafiles) < 1) Нет медиафайлов. @endif
        @endif
        @if ($edit == 1)
            <livewire:edit-mediafile :mediafile="$mediafile" :wire:key="$mediafile->id" :edit="1">
        @endif
        @if ($edit == 2)
            <livewire:edit-mediafile :edit="2">
        @endif
        </div>
    </div>
</div>
@endsection

webapp/resources/views/org.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
        @if(Auth::user()->access_level == 4) <button type="button" class="btn btn-outline-primary my-8" onclick='location.href="{{ route('addorg') }}"'>Добавить организацию (или ИП)</button> @endif
        @if ($edit == 0)
            @foreach ($orgs as $org)
                <livewire:show-org :org="$org" :wire:key="$org->id">
            @endforeach
            @if(count($orgs) > 1){{ $orgs->links() }}@endif
            @if (count($orgs) < 1) Нет организаций или ИП. @endif
        @endif
        </div>
    </div>
</div>
@endsection

webapp/resources/views/post.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
        <button type="button" class="btn btn-outline-primary" onclick='location.href="{{ route('addpost') }}"'>Создать пост</button>
        @if ($edit == 0)
            @foreach ($posts as $post)
                <livewire:show-post :post="$post" :wire:key="$post->id">
            @endforeach
            @if (count($posts) > 1) {{ $posts->links() }} @endif
            @if (count($posts) < 1) Нет постов. @endif
        @endif
        @if ($edit == 1)
            <livewire:edit-post :post="$post" :wire:key="$post->id" :edit="1">
        @endif
        @if ($edit == 2)
            <livewire:edit-post :edit="2">
        @endif
        </div>
    </div>
</div>
@endsection

webapp/resources/views/ticket-buy.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12 bga rounded-3">
            <h3 class="mt-4">Покупка билета</h3>
            <p>Организация-продавец: <b>{{$ot->id}} {{$ot->title}} {{$ot->inn}}</b></p>
            <p>Баланс: <b>{{$uobalance}} руб.</b><form id="topupbalance-user{{$pu->id}}-org{{$ot->id}}" target="_blank" method="POST" action="{{ route('getkvit') }}">@csrf<input name="user_id" type="hidden" value="{{$pu->id}}"><input name="org_id" type="hidden" value="{{$ot->id}}"><button type="submit" class="btn btn-outline-success">Пополнить</button></form></p>
            <h4>{{$bp->title1}}</h4>
            <p>Стоимость: <b>{{$bp->price}} руб.</b></p>
            @if($uobalance < $bp->price)
            <div class="alert alert-danger" role="alert">На Вашем балансе недостаточно средств. Пожалуйста, пополните баланс не менее, чем на {{$bp->price - $uobalance}} руб.</div>
            @else
            <form id="ticketbuy" class="mb-4" method="POST" action="{{ route('ticketbuysubmit') }}">@csrf
                <input name="org_id" type="hidden" value="{{$ot->id}}">
                <input name="post_id" type="hidden" value="{{$bp->id}}">
                <div class="mb-3 form-floating">
                    <input type="number" class="form-control" id="user_id" name="user_id" required readonly value="{{$pu->id}}">
                    <label for="user_id" class="form-label">ID пользователя-приобретателя</label>
                </div>
                <div class="mb-3 form-floating">
                    <input type="number" class="form-control" id="pu" readonly disabled value="{{$pu->id}}">
                    <label for="pu" class="form-label">ID пользователя-плательщика</label>
                </div>
                <button type="submit" class="btn btn-outline-success">Купить</button>
            </form>
            @endif
        </div>
    </div>
</div>
@endsection

webapp/resources/views/user.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
        @if ($edit == 0)
            @foreach ($users as $user)
                <livewire:show-user :user="$user" :wire:key="$user->id">
            @endforeach
            @if (count($users) > 1){{ $users->links() }}@endif
            @if (count($users) < 1) Нет пользователей. @endif
        @endif
        @if ($edit == 1)
            <livewire:edit-user :user="$user" :wire:key="$user->id">
        @endif
        </div>
    </div>
</div>
@endsection